name: Build a container image and push to AWS ECR

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      STAGE:
        required: true
        type: string
      DOCKERFILE:
        required: true
        type: string
    secrets:
      token:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

    outputs:
      IMAGE_URI:
        description: "Docker Image URI"
        value: ${{ jobs.build.outputs.IMAGE_URI }}

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest 
    outputs:
      IMAGE_URI: ${{ steps.build-image.outputs.IMAGE_URI }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: nurigo/${{ inputs.SERVICE_NAME }}
        token: ${{ secrets.token }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.SERVICE_NAME }}
        IMAGE_TAG: ${{ inputs.STAGE }}-${{ github.run_id }}
        DOCKERFILE: ${{ inputs.DOCKERFILE }}
      run: |
        # Build a docker container and push it to ECR 
        docker build -f $DOCKERFILE -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=IMAGE_URI::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Debug
      run: |
        echo "${{ steps.build-image.outputs.IMAGE_URI }}" > ${{ inputs.SERVICE_NAME }}-${{ inputs.STAGE }}-DockerImageURI.txt
        echo "Image URI is ${{ steps.build-image.outputs.IMAGE_URI }}"

    - name: Store Image URI
      uses: actions/upload-artifact@v2
      with:
        name: Image-URI
        path: ${{ inputs.SERVICE_NAME }}-${{ inputs.STAGE }}-DockerImageURI.txt

    - name: Commit yamls
      env:
        BUILD_VERSION: ${{ inputs.STAGE }}-${{ github.run_id }}
      run: |
        echo "${{ env.BUILD_VERSION }}" > build-version
        git config --global user.email "wiley@nurigo.net"
        git config --global user.name "Github Actions"
        git add build-version
        git commit -m "Update build-version ${{ inputs.SERVICE_NAME }} ${{ inputs.STAGE }}"
        git push
