name: Build a container image and push to AWS ECR

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      STAGE:
        required: true
        type: string
      VERSION:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest 
    steps:
    - name: Update manifest
      uses: actions/checkout@v2
      with:
        repository: nurigo/${{ inputs.STAGE }}-manifest
        path: ${{ inputs.STAGE }}-manifest
        token: ${{ secrets.token }}

    - name: Download Image URI
      id: download-image-uri
      uses: actions/download-artifact@v2
      with:
        name: Image-URI

    - name: Read Image URI
      id: read-image-uri
      uses: juliangruber/read-file-action@v1
      with:
        path: ./artifact/${{ inputs.SERVICE_NAME }}-${{ inputs.STAGE }}-DockerImageURI.txt

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Kustomize set image
      env:
        IMAGE_URI: ${{ steps.read-image-uri.outputs.content }}
      working-directory: ./${{ inputs.STAGE }}-manifest/templates/${{ inputs.SERVICE_NAME }}/${{ inputs.VERSION }}
      run: |
        echo "Image Uri: ${{ env.IMAGE_URI }}"
        kustomize edit set image IMAGE_URI=${{ env.IMAGE_URI }}

    - name: Kustomize build and commit yamls
      working-directory: ./${{ inputs.STAGE }}-manifest
      run: |
        kustomize build templates/${{ inputs.SERVICE_NAME }}/${{ inputs.VERSION }} > ${{ inputs.STAGE }}/${{ inputs.SERVICE_NAME }}-${{ inputs.VERSION }}.yaml
        git config --global user.email "wiley@nurigo.net"
        git config --global user.name "Github Actions"
        git add ${{ inputs.STAGE }}
        git commit -m "Update ${{ inputs.SERVICE_NAME }} image tag to ${{ inputs.STAGE }}-${{ github.run_id }}"
        git push
